// ==========================================
//  Generated by Script (see /script/index.ts)
//  DO NOT EDIT THIS FILE DIRECTLY
//  In "/src/parser/generated_ast.rs"
// ==========================================

use crate::compiler::arena::{ArenaIter, ArenaBox};
use crate::tokenizer::tokens::Token;
use crate::parser::ast::ASTNode;
use crate::parser::ast::SyncPointBitMap;
use crate::parser::errors::ParseErr;


impl ASTNode for Module {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Module {
    pub declarations: ArenaIter<TopLevelDeclaration>,
}

impl ASTNode for TopLevelDeclaration {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        Some(Self::Invalid)
    }

    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum TopLevelDeclaration {
    Function(Function),
    Invalid,
}

impl ASTNode for Function {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Function {
    pub name: Identifier,
    pub params: ArenaIter<Parameter>,
    pub return_type: Option<TypeLiteral>,
    pub body: BlockExpression,
}

impl ASTNode for Parameter {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Parameter {
    pub name: Identifier,
}

impl ASTNode for BlockExpression {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct BlockExpression {
    pub statements: ArenaIter<Statement>,
    pub final_expr: Option<Expression>,
}

impl ASTNode for Statement {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        Some(Self::Invalid)
    }

    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum Statement {
    ExpressionStmt(ExpressionStmt),
    Assignment(Assignment),
    Return(Return),
    Invalid,
}

impl ASTNode for ExpressionStmt {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct ExpressionStmt {
    pub expr: Expression,
}

impl ASTNode for Assignment {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Assignment {
    pub name: Identifier,
    pub value: Expression,
}

impl ASTNode for Return {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Return {
    pub value: Option<Expression>,
}

impl ASTNode for Expression {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        Some(Self::Invalid)
    }

    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum Expression {
    LiteralAST(LiteralAST),
    FunctionCall(FunctionCall),
    Invalid,
}

impl ASTNode for LiteralAST {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct LiteralAST {
    pub value: StringLiteral,
}

impl ASTNode for FunctionCall {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct FunctionCall {
    pub name: Identifier,
    pub args: ArenaIter<Expression>,
}

impl ASTNode for TypeLiteral {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        Some(Self::Invalid)
    }

    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum TypeLiteral {
    IntType(IntType),
    Invalid,
}

impl ASTNode for IntType {
    const SYNC_POINT_SETS: SyncPointBitMap = SyncPointBitMap::build_map(&[], false, false, false);
    fn get_error_situation(err: ParseErr) -> Option<Self> {
        None
    }
    fn is_sync_point(token: Option<&Token>) -> bool { false }
}
#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct IntType {

}

pub use crate::parser::manual_ast::Identifier;

pub use crate::parser::manual_ast::StringLiteral;