// ==========================================
//  Generated by Script (see /script/index.ts)
//  DO NOT EDIT THIS FILE DIRECTLY
//  In "/src/parser/generated_ast.rs"
// ==========================================

use crate::compiler::arena::{ArenaBox, ArenaIter};

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Module {
    pub declarations: ArenaIter<TopLevelDeclaration>,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum TopLevelDeclaration {
    Function(Function),
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Function {
    pub name: Identifier,
    pub params: ArenaIter<Parameter>,
    pub return_type: Option<TypeLiteral>,
    pub body: BlockExpression,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Parameter {
    pub name: Identifier,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct BlockExpression {
    pub statements: ArenaIter<Statement>,
    pub final_expr: Option<Expression>,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum Statement {
    ExpressionStmt(ExpressionStmt),
    Assignment(Assignment),
    Return(Return),
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct ExpressionStmt {
    pub expr: Expression,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Assignment {
    pub name: Identifier,
    pub value: Expression,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Return {
    pub value: Option<Expression>,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum Expression {
    LiteralAST(LiteralAST),
    FunctionCall(FunctionCall),
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct LiteralAST {
    pub value: StringLiteral,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct FunctionCall {
    pub name: Identifier,
    pub args: ArenaIter<Expression>,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub enum TypeLiteral {
    IntType(IntType),
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct IntType {}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct Identifier {
    pub a1: _a1,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct StringLiteral {
    pub a1: _a1,
}

#[derive(Debug, Copy, Clone, std::hash::Hash, PartialEq, Eq)]
pub struct A1 {}
