use crate::compiler::runtime::{Engine, Query};
use crate::compiler::{
    arena::{Arena, ArenaBox},
    context::frontend::CompilerFrontendContext,
    source_holder::SourceHolder,
    symbol::SymbolFactory,
};
use crate::diagnostic::stream::StockDiagnosticStream;
use crate::diagnostic::Diagnostic;
use crate::parser::ast::ASTVisitor;
use crate::parser::tracer::LogTracer;
use crate::parser::{generated_ast_printer::ASTPrinter, parse::Parser};
use crate::tokenizer::token_stream::TokenStream;
use crate::tokenizer::tokenize::Tokenizer;
use std::fmt::Display;

#[cfg(test)]
mod tests;

mod ast_node;
mod base_parser;
mod diagnostic;
mod errors;
mod generated_ast; // generated by script
mod generated_ast_printer;
mod generated_parser; // generated by script
mod manual_ast;
mod manual_parser;
mod recovery;
pub mod parse;
pub mod tracer;

pub mod ast {
    pub use crate::parser::generated_ast::*;
}

pub struct Ast<'src> {
    ast: ArenaBox<generated_ast::Module>,
    ast_arena: Arena,
    symbols: SymbolFactory<'src>,
    source_holder: SourceHolder<'src>,
}

impl<'src> Ast<'src> {
    pub fn new(
        ast: ArenaBox<generated_ast::Module>,
        arena: Arena,
        source_holder: SourceHolder<'src>,
        symbols: SymbolFactory<'src>,
    ) -> Self {
        Self {
            ast,
            ast_arena: arena,
            symbols,
            source_holder,
        }
    }
}

impl<'src> Display for Ast<'src> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut printer = ASTPrinter {
            symbols: &self.symbols,
            arena: &self.ast_arena,
            source_holder: &self.source_holder,
            writer: f,
        };
        printer.visit_Module(self.ast.get(&self.ast_arena))
    }
}

pub struct ParseFileQuery;
impl Query for ParseFileQuery {
    type From = String;
    type To = ();
    fn run<E: Engine>(engine: &E, src_path: Self::From) -> Self::To {
        // let src = engine.fetch::<ReadFileQuery>(src_path);
        // let source_holder = SourceHolder::new(&src);
        // let ast_arena = Arena::new();
        // let errors_arena = Arena::new();
        // let mut ctx = CompilerFrontendContext {
        //     source: source_holder,
        //     symbol_factory: SymbolFactory::new(source_holder),
        //     ast_arena: &ast_arena,
        //     errors_arena: &ast_arena,
        // };

        // let tokens = {
        //     let tokenizer = Tokenizer::new(&src, &mut ctx.symbol_factory);
        //     let (tokens, _) = tokenizer.tokenize();
        //     tokens
        // };

        // let parser = Parser::new(TokenStream::new(tokens), ctx);
        // let ast = parser
        //     .parse()
        //     .map_err(<ParseErr as Into<Box<dyn CompilerDiagnostic>>>::into);

        // // TODO: construct parse result and return

        todo!()
    }
}

pub fn parse_for_test<'a>(source: &'a str) -> (Ast<'a>, Vec<Diagnostic>) {
    let mut diagnostic_stream = StockDiagnosticStream::new();
    let mut symbols = SymbolFactory::new(source);
    let tokenizer = Tokenizer::new(source, &mut symbols);
    let (tokens, line_starts) = tokenizer.tokenize(&mut diagnostic_stream);
    let stream = TokenStream::new(tokens);
    let mut ast_arena = Arena::new();
    let mut parser: Parser<'_, '_, '_, _, LogTracer> = Parser::new(
        stream,
        CompilerFrontendContext {
            source,
            symbol_factory: &mut symbols,
            ast_arena: &mut ast_arena,
        },
        &mut diagnostic_stream,
    );
    let ast = parser.parse();

    let ast = Ast::new(
        ast,
        ast_arena,
        SourceHolder::new(source, line_starts),
        symbols,
    );

    (ast, diagnostic_stream.into_vec())
}
