import { astName, RustASTTypeName } from "./ir";

export function generateASTSizeCheckerRustTest(astTypes: RustASTTypeName[]): string {
    let ret = "";
    ret += `// ==========================================\n`;
    ret += `//  Generated by Script (see /script/index.ts)\n`;
    ret += `//  DO NOT EDIT THIS FILE DIRECTLY\n`;
    ret += `//  In "/src/parser/tests/ast_size_checker.rs"\n`;
    ret += `// ==========================================\n\n`;
    ret += `use crate::parser::generated_ast::*;\n\n`;
    ret += `#[test]\n`;
    ret += `#[ignore]\n`;
    ret += `fn report_ast_size() {\n`;
    ret += `    println!("===BEGIN_REPORT===");\n`
    for (const ast of astTypes) {
        ret += `    println!("${ast}:{}", size_of::<${ast}>());\n`
    }
    ret += `    println!("===END_REPORT===");\n`
    ret += `}\n`;
    return ret;
}

export function parseASTSizeCheckerResult(result: string): { ast: RustASTTypeName, size: number}[] {
    const report = result.substring(result.indexOf("===BEGIN_REPORT==="), result.indexOf("===END_REPORT==="));
    return report.split("\n").map(line => {
        const separed = line.split(":");
        const ast = astName(separed[0]);
        const size = parseInt(separed[1]);
        return { ast, size };
    });
}
