import { IR, BranchParserFunction, ProductParserFunction, HookParserFunction } from "./ir";
import { getUniqueVariants } from "./gen";

export class ParserGenerator {
    public generateParser(ir: IR): string {
        const funcs = [];
        for (const func of ir) {
            switch (func.kind) {
                case "branch":
                    funcs.push(this.generateBranchParseFunction(func));
                    break;
                case "product":
                    funcs.push(this.generateProductParserFunction(func));
                    break;
                case "hook":
                    funcs.push(this.generateHookParserFunction(func));
                    break;
            }
        }
        let ret = "";
        ret += `// ==========================================\n`;
        ret += `//  Generated by Script (see /script/index.ts)\n`;
        ret += `//  DO NOT EDIT THIS FILE DIRECTLY\n`;
        ret += `//  In "/src/parser/generated_parser.rs"\n`;
        ret += `// ==========================================\n\n`;
        ret += `#![allow(unused_variables)]\n\n`;
        ret += `use crate::parser::base_parser::BaseParser;\n`;
        ret += `use crate::parser::errors::IParseErr;\n`;
        ret += `use crate::tokenizer::tokens::{Delimiter, Keyword, Literal, Operator, Comment, Token};\n\n`;
        ret += `#[allow(clippy::wildcard_imports)]\n`;
        ret += `use crate::parser::generated_ast::*;\n\n`;
        ret += `#[allow(non_snake_case)]\n`;
        ret += `pub trait GeneratedParser: BaseParser + Sized {`;
        ret += funcs.join("");
        ret += `}`;
        return ret;
    }

    private generateBranchParseFunction(func: BranchParserFunction): string {
        let ret = "";
        ret += `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error> {\n`;

        if (func.branchesJudgebleInPeek0.length === 0 &&
            func.branchesJudgebleInPeek1.length === 0 &&
            (func.branchesFallbackInPeek1 || []).length === 0 &&
            func.branchesNeedBacktrack.length === 0) {
            ret += `        Err(Self::Error::build(false, &[], self.enviroment()))\n`;
            ret += `    }\n`;
            return ret;
        }

        ret += `        match self.peek::<0>() {\n`;

        const peek0Groups = new Map<string, { isBoxed: boolean, terminals: Set<string> }>();
        for (const branch of func.branchesJudgebleInPeek0) {
            if (!peek0Groups.has(branch.astTypeName)) {
                peek0Groups.set(branch.astTypeName, { isBoxed: branch.isBoxed, terminals: new Set() });
            }
            peek0Groups.get(branch.astTypeName)!.terminals.add(branch.firstTerminal.replace(/\$.*\$/, "_"));
        }
        const sortedKeys = Array.from(peek0Groups.keys()).sort();
        for (const astType of sortedKeys) {
            const pattern = Array.from(peek0Groups.get(astType)!.terminals).sort().join(" | ");
            const parseCall = peek0Groups.get(astType)!.isBoxed 
                ? `self.alloc_box(|this| this.parse_${astType}())?` 
                : `self.parse_${astType}()?`;
            ret += `            Some(${pattern}) => Ok(${func.astTypeName}::${astType}(${parseCall})),\n`;
        }

        const complexFirstTerminals = [...new Set([
            ...func.branchesJudgebleInPeek1.map(b => b.firstTerminal),
            ...func.branchesNeedBacktrack.map(b => b.firstTerminal),
            ...(func.branchesFallbackInPeek1 || []).map(b => b.firstTerminal)
        ])];

        for (const t0 of complexFirstTerminals.sort()) {
            const cleanT0 = t0.replace(/\$.*\$/, "_");
            ret += `            Some(${cleanT0}) => match self.peek::<1>() {\n`;

            const peek1 = func.branchesJudgebleInPeek1.filter(b => b.firstTerminal === t0);

            const peek1Groups = new Map<string, { isBoxed: boolean, terminals: Set<string> }>();
            for (const branch of peek1) {
                if (!peek1Groups.has(branch.astTypeName)) {
                    peek1Groups.set(branch.astTypeName, { isBoxed: branch.isBoxed, terminals: new Set() });
                }
                peek1Groups.get(branch.astTypeName)!.terminals.add(branch.secondTerminal.replace(/\$.*\$/, "_"));
            }

            for (const [astType, group] of peek1Groups.entries()) {
                const pattern = Array.from(group.terminals).join(" | ");
                const parseCall = group.isBoxed 
                    ? `self.alloc_box(|this| this.parse_${astType}())?` 
                    : `self.parse_${astType}()?`;
                ret += `                Some(${pattern}) => Ok(${func.astTypeName}::${astType}(${parseCall})),\n`;
            }

            const backtrack = func.branchesNeedBacktrack.filter(b => b.firstTerminal === t0);
            if (backtrack.length > 0) {
                ret += `                _ => {\n`;
                for (const b of backtrack) {
                    const wrapCall = b.isBoxed ? `self.alloc(node)` : `node`;
                    ret += `                    if let Ok(node) = self.backtrack(|this| this.parse_${b.astTypeName}()) {\n`;
                    ret += `                        return Ok(${func.astTypeName}::${b.astTypeName}(${wrapCall}));\n`;
                    ret += `                    }\n`;
                }
                ret += `                    Err(Self::Error::build(false, &[], self.enviroment()))\n`;
                ret += `                }\n`;
            } else {
                const fallback = (func.branchesFallbackInPeek1 || []).find(b => b.firstTerminal === t0);
                if (fallback) {
                    const parseCall = fallback.isBoxed 
                        ? `self.alloc_box(|this| this.parse_${fallback.astTypeName}())?` 
                        : `self.parse_${fallback.astTypeName}()?`;
                    ret += `                _ => Ok(${func.astTypeName}::${fallback.astTypeName}(${parseCall})),\n`;
                } else {
                    ret += `                _ => Err(Self::Error::build(false, &[], self.enviroment())),\n`;
                }
            }
            ret += `            },\n`;
        }

        const expected = [...new Set(func.expectedTerminals.filter(t => !t.includes("$") && !t.includes("_")))];
        const hasCustomMatch = func.expectedTerminals.some(t => t.includes("$"));
        
        ret += `            _ => Err(Self::Error::build(\n`;
        ret += `                ${hasCustomMatch},\n`;
        ret += `                &[${expected.join(", ")}],\n`;
        ret += `                self.enviroment(),\n`;
        ret += `            )),\n`;
        ret += `        }\n`;
        ret += `    }\n`;

        return ret;
    }

    private generateProductParserFunction(func: ProductParserFunction): string {
        let ret = "";
        let isManual = func.elements.some(element => element.kind === "terminal" && element.tokenTypeName.includes("$"));
        if (isManual) {
            ret += `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error>;\n`;
            return ret;
        }
        ret += `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error> {\n`;
        for (const element of func.elements) {
            switch (element.kind) {
                case "normal":
                    ret += `        let v_${element.astTypeName} = self.parse_${element.astTypeName}()?;\n`;
                    break;
                case "boxed":
                    ret += `        let v_${element.astTypeName} = self.alloc_box(|this| this.parse_${element.astTypeName}())?;\n`;
                    break;
                case "option":
                    ret += `        let v_${element.astTypeName} = self.optional(|this| this.parse_${element.astTypeName}());\n`;
                    break;
                case "repeat":
                    ret += `        let v_${element.astTypeName} = self.repeat(Self::parse_${element.astTypeName})?;\n`;
                    break;
                case "optionWithBox":
                    ret += `        let v_${element.astTypeName} = self.optional_box(|this| this.parse_${element.astTypeName}());\n`;
                    break;
                case "terminal":
                    if (!element.tokenTypeName.includes("$")) {
                        ret += `        self.expect(&${element.tokenTypeName})?;\n`;
                    }
                    break;
            }
        }
        ret += `        Ok(${func.astTypeName} {\n`;
        const sortedElements = [...func.elements].sort((a, b) => {
            const nameA = a.kind === 'terminal' ? a.tokenTypeName : a.astTypeName;
            const nameB = b.kind === 'terminal' ? b.tokenTypeName : b.astTypeName;
            return nameA.localeCompare(nameB);
        });
        for (const element of sortedElements) {
            if (element.kind !== "terminal") {
                ret += `            ${element.astTypeName}: v_${element.astTypeName},\n`;
            }
        }
        ret += `        })\n`;
        ret += `    }\n`;
        return ret;
    }

    private generateHookParserFunction(func: HookParserFunction): string {
        return `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error>;\n`;
    }

}

