import { IR, BranchParserFunction, ProductParserFunction, HookParserFunction } from "./ir";
import { getUniqueVariants } from "./gen";

export class ParserGenerator {
    public generateParser(ir: IR): string {
        const funcs = [];
        for (const func of ir) {
            switch (func.kind) {
                case "branch":
                    funcs.push(this.generateBranchParseFunction(func));
                    break;
                case "product":
                    funcs.push(this.generateProductParserFunction(func));
                    break;
                case "hook":
                    funcs.push(this.generateHookParserFunction(func));
                    break;
            }
        }
        let ret = "";
        ret += `// ==========================================\n`;
        ret += `//  Generated by Script (see /script/index.ts)\n`;
        ret += `//  DO NOT EDIT THIS FILE DIRECTLY\n`;
        ret += `//  In "/src/parser/generated_parser.rs"\n`;
        ret += `// ==========================================\n\n`;
        ret += `use crate::compiler::symbol::Symbol;\n`;
        ret += `use crate::parser::base_parser::BaseParser;\n`;
        ret += `use crate::parser::ast_node::ASTNode;\n`;
        ret += `use crate::parser::errors::IParseErr;\n`;
        ret += `use crate::tokenizer::tokens::{Delimiter, Keyword, Literal, Operator, Comment, Token};\n\n`;
        ret += `#[allow(clippy::wildcard_imports)]\n`;
        ret += `use crate::parser::generated_ast::*;\n\n`;
        ret += `#[allow(non_snake_case)]\n`;
        ret += `pub trait GeneratedParser: BaseParser + Sized {`;
        ret += funcs.join("");
        ret += `}`;
        return ret;
    }

    private generateBranchParseFunction(func: BranchParserFunction): string {
        const variants = getUniqueVariants(func);
        let ret = "";
        ret += `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error> {\n`;

        if (variants.length === 0) {
            ret += `        Err(Self::Error::build(self.get_errors_arena(), false, &[], self.enviroment()))\n`;
            ret += `    }\n`;
            return ret;
        }

        ret += `        let p0 = self.peek::<0>();\n\n`;

        for (const v of variants) {
            ret += `        let is_${v.name}_1 = ${v.name}::is_first_sets(&p0);\n`;
        }

        const expr = variants.map(v => `(is_${v.name}_1 as u8)`).join(" + ");
        ret += `        let count_1 = ${expr};\n`;

        ret += `        if count_1 == 1 {\n`;
        for (const v of variants) {
            let parseCall = v.isBoxed ? `self.alloc_box(|this| this.parse_${v.name}())?` : `self.parse_${v.name}()?`;
            ret += `            if is_${v.name}_1 { return Ok(${func.astTypeName}::${v.name}(${parseCall})); }\n`;
        }

        ret += `        } else if count_1 > 1 {\n`;
        for (const v of variants) {
            ret += `            if is_${v.name}_1 {\n`;
            ret += `                if let Ok(node) = self.backtrack(|this| this.parse_${v.name}()) {\n`;
            if (v.isBoxed) {
                ret += `                    return Ok(${func.astTypeName}::${v.name}(self.alloc(node)));\n`;
            } else {
                ret += `                    return Ok(${func.astTypeName}::${v.name}(node));\n`;
            }
            ret += `                }\n`;
            ret += `            }\n`;
        }
        ret += `        }\n\n`;

        for (const v of variants) {
            ret += `        if let Ok(node) = self.backtrack(|this| this.parse_${v.name}()) {\n`;
            if (v.isBoxed) {
                ret += `            return Ok(${func.astTypeName}::${v.name}(self.alloc(node)));\n`;
            } else {
                ret += `            return Ok(${func.astTypeName}::${v.name}(node));\n`;
            }
            ret += `        }\n`;
        }

        ret += `\n        Err(Self::Error::build(\n`;
        ret += `            self.get_errors_arena(),\n`;
        ret += `            ${func.expectedTerminals.some(t => t.includes("$")) ? "true" : "false"},\n`;
        const expected = [...new Set(func.expectedTerminals.filter(t => !t.includes("$") && !t.includes("_")))];
        ret += `            &[${expected.join(", ")}],\n`;
        ret += `            self.enviroment(),\n`;
        ret += `        ))\n`;
        ret += `    }\n`;

        return ret;
    }

    private generateProductParserFunction(func: ProductParserFunction): string {
        let ret = "";
        let isManual = func.elements.some(element => element.kind === "terminal" && element.tokenTypeName.includes("$"));
        if (isManual) {
            ret += `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error>;\n`;
            return ret;
        }
        ret += `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error> {\n`;
        for (const element of func.elements) {
            switch (element.kind) {
                case "normal":
                    ret += `        let v_${element.astTypeName} = self.parse_${element.astTypeName}()?;\n`;
                    break;
                case "boxed":
                    ret += `        let v_${element.astTypeName} = self.alloc_box(|this| this.parse_${element.astTypeName}())?;\n`;
                    break;
                case "option":
                    ret += `        let v_${element.astTypeName} = self.parse_${element.astTypeName}().ok();\n`;
                    break;
                case "repeat":
                    ret += `        let v_${element.astTypeName} = self.repeat(Self::parse_${element.astTypeName})?;\n`;
                    break;
                case "optionWithBox":
                    ret += `        let v_${element.astTypeName} = self.alloc_box(Self::parse_${element.astTypeName}).ok();\n`;
                    break;
                case "terminal":
                    if (!element.tokenTypeName.includes("$")) {
                        ret += `        self.expect(&${element.tokenTypeName})?;\n`;
                    }
                    break;
            }
        }
        ret += `        Ok(${func.astTypeName} {\n`;
        for (const element of func.elements.sort()) {
            if (element.kind !== "terminal") {
                ret += `            ${element.astTypeName}: v_${element.astTypeName},\n`;
            }
        }
        ret += `        })\n`;
        ret += `    }\n`;
        return ret;
    }

    private generateHookParserFunction(func: HookParserFunction): string {
        return `\n    fn parse_${func.functionName}(&mut self) -> Result<${func.astTypeName}, Self::Error>;\n`;
    }

}

