import { IR } from "./ir";
import { getUniqueVariants } from "./gen";

export class ASTPrinterGenerator {
    public generateAstPrinterImpl(ir: IR): string {
        let ret = "";
        ret += `// ==========================================\n`;
        ret += `//  Generated by Script (see /script/index.ts)\n`;
        ret += `//  DO NOT EDIT THIS FILE DIRECTLY\n`;
        ret += `//  In "/src/parser/generated_ast_printer.rs"\n`;
        ret += `// ==========================================\n\n`;
        ret += "use crate::compiler::{arena::Arena, symbol::SymbolFactory, source_holder::SourceHolder};\n";
        ret += "use crate::parser::generated_ast::*;\n";
        ret += "use crate::parser::ast_node::ASTNode;\n";
        ret += "\n";
        ret += "pub struct ASTPrinter<'a, 'f, 'b, 'src> {\n";
        ret += "    pub arena: &'a Arena,\n";
        ret += "    pub symbols: &'a SymbolFactory<'src>,\n";
        ret += "    pub source_holder: &'a SourceHolder<'src>,\n";
        ret += "    pub writer: &'f mut std::fmt::Formatter<'b>,\n";
        ret += "}\n";
        ret += "\n";
        ret += "impl<'a, 'f, 'b, 'src> ASTPrinter<'a, 'f, 'b, 'src> {\n";
        ret += "    fn write(&mut self, s: &str) -> Result<(), std::fmt::Error> {\n";
        ret += "        self.writer.write_str(s);\n";
        ret += "        Ok(())\n";
        ret += "    }";
        ret += "}\n\n";

        ret += "#[allow(clippy::unused_unit)]\n";
        ret += "#[allow(non_snake_case)]\n";
        ret += "impl<'a, 'f, 'b, 'src> ASTVisitor for ASTPrinter<'a, 'f, 'b, 'src> {\n";
        ret += "    type ReturnType = Result<(), std::fmt::Error>;\n";

        for (const func of ir) {
            ret += `    fn visit_${func.astTypeName}(&mut self, node: &${func.astTypeName}) -> Result<(), std::fmt::Error> {\n`;

            if (func.kind === "branch") {
                ret += `        match node {\n`;
                const variants = getUniqueVariants(func);
                for (const variant of variants) {
                    const inner = variant.isBoxed ? "v.get(self.arena)" : "v";
                    ret += `            ${func.astTypeName}::${variant.name}(v) => {\n`;
                    ret += `                self.write(r#"{"kind":"${variant.name}","value":"#)?;\n`;
                    ret += `                ${inner}.accept(self)?;\n`;
                    ret += `                self.write("}")?;\n`;
                    ret += `            }\n`;
                }
                ret += `            ${func.astTypeName}::Invalid => self.write("null")?,\n`;
                ret += `        }\n`;

            } else if (func.kind === "product") {
                const isManual = func.elements.some(el => el.kind === "terminal" && el.tokenTypeName.includes("$"));

                if (isManual) {
                    ret += `        self.write(r#"{"type":"${func.astTypeName}","value":"#)?;\n`;

                    // WARNING: hardcode identifier and string literal behavior
                    if (func.astTypeName == "Identifier") {
                        ret += `        self.write(&format!("\\"{}\\"", self.symbols.get(&node.symbol)))?;\n`;
                    } else if (func.astTypeName == "StringLiteral") {
                        ret += `        self.write(&format!("\\"{}\\"", node.span.into(self.source_holder.get())))?;\n`;
                    } else {
                        ret += `        self.write(&format!(r#""{:?}""#, node))?;\n`;
                    }

                    ret += `        self.write("}")?;\n`;
                } else {
                    ret += `        self.write(r#"{"type":"${func.astTypeName}""#)?;\n`;
                    for (const el of func.elements) {
                        if (el.kind === "terminal") continue;

                        ret += `        self.write(r#","${el.astTypeName}":"#)?;\n`;
                        switch (el.kind) {
                            case "normal":
                                ret += `        node.${el.astTypeName}.accept(self)?;\n`;
                                break;
                            case "boxed":
                                ret += `        node.${el.astTypeName}.get(self.arena).accept(self)?;\n`;
                                break;
                            case "option":
                                ret += `        if let Some(v) = &node.${el.astTypeName} { v.accept(self)? } else { self.write("null")? };\n`;
                                break;
                            case "optionWithBox":
                                ret += `        if let Some(v) = &node.${el.astTypeName} { v.get(self.arena).accept(self)? } else { self.write("null")? };\n`;
                                break;
                            case "repeat":
                                ret += `        self.write("[")?;\n`;
                                ret += `        let mut first = true;\n`;
                                ret += `        for item in node.${el.astTypeName}.into_ref(self.arena) {\n`;
                                ret += `            if !first { self.write(",")?; }\n`;
                                ret += `            item.accept(self)?;\n`;
                                ret += `            first = false;\n`;
                                ret += `        }\n`;
                                ret += `        self.write("]")?;\n`;
                                break;
                        }
                    }
                    ret += `        self.write("}")?;\n`;
                }

            } else if (func.kind === "hook") {
                ret += `        self.write(r#"{"type":"${func.astTypeName}","hook":true}"#)?;\n`;
            }

            ret += "        Ok(())\n";
            ret += `    }\n\n`;
        }
        ret += `}`
        return ret;
    }
}
