import { IR, BranchParserFunction, ProductParserFunction, HookParserFunction } from "./ir";

export class ASTTypeGenerator {
    public generateASTType(ir: IR): string {
        let decls = [];
        decls.push(this.generateVisitorTrait(ir));
        const sortedIR = [...ir].sort((a, b) => a.astTypeName.localeCompare(b.astTypeName));
        for (const element of sortedIR) {
            switch (element.kind) {
                case "branch":
                    decls.push(this.generateBranchASTType(element));
                    break;
                case "product":
                    decls.push(this.generateProductASTType(element));
                    break;
                case "hook":
                    decls.push(this.generateHookASTType(element));
                    break;
            }
        }
        let ret = "";
        ret += `// ==========================================\n`;
        ret += `//  Generated by Script (see /script/index.ts)\n`;
        ret += `//  DO NOT EDIT THIS FILE DIRECTLY\n`;
        ret += `//  In "/src/parser/generated_ast.rs"\n`;
        ret += `// ==========================================\n\n`;
        ret += `#![allow(non_snake_case)]\n`;
        ret += `#![allow(nonstandard_style)]\n\n`;
        ret += `use crate::compiler::arena::{ArenaBox, ArenaIter};\n`;
        ret += `use crate::parser::ast_node::{ASTNode, Node};\n`;
        ret += `use crate::parser::ast_node::TokenBitMap;\n`;
        ret += `use crate::parser::errors::ParseErr;\n`;
        ret += `use crate::tokenizer::tokens::{Token, Delimiter, Keyword, Operator};\n\n`;
        ret += decls.join("");
        return ret;
    }

    private generateVisitorTrait(ir: IR): string {
        let ret = "";
        ret += `pub trait ASTVisitor {\n`;
        ret += `    type ReturnType;`;
        const elements = [...new Set(ir.map(({ astTypeName }) => astTypeName))].sort((pre, curr) => pre.localeCompare(curr));
        for (const element of elements) {
            ret += `    fn visit_${element}(&mut self, node: &${element}) -> Self::ReturnType;\n`;
        }
        ret += `}\n\n`;

        return ret;
    }

    private generateBranchASTType(func: BranchParserFunction): string {
        let ret = "";
        ret += `#[derive(Copy, Clone, Debug, std::hash::Hash, PartialEq, Eq)]\n`;
        ret += `pub enum ${func.astTypeName} {\n`;

        const allVariants = [
            ...func.branchesJudgebleInPeek0,
            ...func.branchesJudgebleInPeek1,
            ...(func.branchesFallbackInPeek1 || []),
            ...func.branchesNeedBacktrack
        ];
        let dublicateRemoved = [...new Set(allVariants.map(branch => branch.astTypeName))].sort();

        for (const typeName of dublicateRemoved) {
            const isBoxed = allVariants.some(branch => branch.astTypeName === typeName && branch.isBoxed);
            if (isBoxed) {
                ret += `    ${typeName}(ArenaBox<${typeName}>),\n`;
            } else {
                ret += `    ${typeName}(${typeName}),\n`;
            }
        }
        ret += `    Invalid,\n`;
        ret += `}\n\n`;

        ret += `impl ASTNode for ${func.astTypeName} {\n`;
        const syncHasIdentifier = func.syncPointsTerminals.some(t => t.includes("Identifier"));
        const syncHasLiteral = func.syncPointsTerminals.some(t => t.includes("Literal"));
        const syncPoints = [...new Set(func.syncPointsTerminals.filter(t => !t.includes("$") && !t.includes("_")))].sort().join(", ");
        const first1Sets = func.firstTerminals.map(v => v.split(",")[0]);
        const first1HasIdentifier = first1Sets.some(t => t.includes("Identifier"));
        const first1HasLiteral = first1Sets.some(t => t.includes("Literal"));
        const first1Points = [...new Set(first1Sets.filter(t => !t.includes("$")))].sort().join(", ");
        const first2Sets = func.firstTerminals.map(v => v.split(",")[1]).filter(v => v !== undefined);
        const first2HasIdentifier = first2Sets.some(t => t.includes("Identifier"));
        const first2HasLiteral = first2Sets.some(t => t.includes("Literal"));
        const first2Points = [...new Set(first2Sets.filter(t => !t.includes("$")))].sort().join(", ");
        ret += `    const FOLLOW_SETS: TokenBitMap = TokenBitMap::build_map(${syncHasIdentifier}, ${syncHasLiteral}, true, &[${syncPoints}]);\n`;
        ret += `    const FIRST_1_SETS: TokenBitMap = TokenBitMap::build_map(${first1HasIdentifier}, ${first1HasLiteral}, false, &[${first1Points}]);\n`;
        ret += `    const FIRST_2_SETS: TokenBitMap = TokenBitMap::build_map(${first2HasIdentifier}, ${first2HasLiteral}, false, &[${first2Points}]);\n\n`;
        ret += `    fn get_error_situation(_: ParseErr) -> Option<Self> {\n`;
        ret += `        Some(Self::Invalid)\n`;
        ret += `    }\n\n`;
        ret += `    fn name() -> &'static str { "${func.astTypeName}" }\n`;
        ret += `    type Target = Self;\n`;
        ret += `}\n\n`;

        ret += `impl ${func.astTypeName} {\n`;
        const everyVariants = (() => {
            const list = [...func.branchesFallbackInPeek1, ...func.branchesJudgebleInPeek0, ...func.branchesJudgebleInPeek1, ...func.branchesNeedBacktrack];
            const taken = [...new Map(
                list.map(item => {
                    const key = `${item.astTypeName}-${item.isBoxed}`;
                    return [key, { name: item.astTypeName, isBoxed: item.isBoxed }];
                })
            )];
            return [...new Set(taken)].map(v => v[1]).sort((a, b) => a.name.localeCompare(b.name));
        })();
        for (const variant of everyVariants) {
            let returnType;
            if (variant.isBoxed) {
                returnType = "ArenaBox<" + variant.name + ">";
            } else {
                returnType = variant.name;
            }

            ret += `    pub fn expect_${variant.name}(&mut self) -> Option<&mut ${returnType}> {\n`;
            ret += `        match self {\n`;
            ret += `            Self::${variant.name}(v) => Some(&mut *v),\n`;
            ret += `            _ => None,\n`;
            ret += `        }\n`;
            ret += `    }\n\n`;
        }
        ret += `}\n\n`;

        ret += `impl Node for ${func.astTypeName} {\n`;
        ret += `    fn accept<V: ASTVisitor>(&self, visitor: &mut V) -> V::ReturnType {\n`;
        ret += `        visitor.visit_${func.astTypeName}(self)\n`;
        ret += `    }\n`
        ret += `}\n\n`;
        return ret;
    }

    private generateProductASTType(func: ProductParserFunction): string {
        let ret = "";
        const isManual = func.elements.some(element => element.kind === "terminal" && element.tokenTypeName.includes("$"));
        if (isManual) {
            ret += `pub use crate::parser::manual_ast::${func.astTypeName};\n\n`;
        } else {
            ret += `#[derive(Copy, Clone, Debug, std::hash::Hash, PartialEq, Eq)]\n`;
            ret += `pub struct ${func.astTypeName} {\n`;
            for (const element of func.elements) {
                switch (element.kind) {
                    case "normal":
                        ret += `    pub(super) ${element.name}: ${element.astTypeName},\n`;
                        break;
                    case "boxed":
                        ret += `    pub(super) ${element.name}: ArenaBox<${element.astTypeName}>,\n`;
                        break;
                    case "option":
                        ret += `    pub(super) ${element.name}: Option<${element.astTypeName}>,\n`;
                        break;
                    case "optionWithBox":
                        ret += `    pub(super) ${element.name}: Option<ArenaBox<${element.astTypeName}>>,\n`;
                        break;
                    case "repeat":
                        ret += `    pub(super) ${element.name}: ArenaIter<${element.astTypeName}>,\n`;
                        break;
                }
            }
            ret += `}\n\n`;
        }
        ret += `impl ASTNode for ${func.astTypeName} {\n`;
        const syncHasIdentifier = func.syncPointsTerminals.some(t => t.includes("Identifier"));
        const syncHasLiteral = func.syncPointsTerminals.some(t => t.includes("Literal"));
        const syncPoints = func.syncPointsTerminals.filter(t => !t.includes("$")).join(", ");
        const first1Sets = func.firstTerminals.map(v => v.split(",")[0]);
        const first1HasIdentifier = first1Sets.some(t => t.includes("Identifier"));
        const first1HasLiteral = first1Sets.some(t => t.includes("Literal"));
        const first1Points = first1Sets.filter(t => !t.includes("$")).join(", ");
        const first2Sets = func.firstTerminals.map(v => v.split(",")[1]).filter(v => v !== undefined);
        const first2HasIdentifier = first2Sets.some(t => t.includes("Identifier"));
        const first2HasLiteral = first2Sets.some(t => t.includes("Literal"));
        const first2Points = first2Sets.filter(t => !t.includes("$")).join(", ");
        ret += `    const FOLLOW_SETS: TokenBitMap = TokenBitMap::build_map(${syncHasIdentifier}, ${syncHasLiteral}, true, &[${syncPoints}]);\n`;
        ret += `    const FIRST_1_SETS: TokenBitMap = TokenBitMap::build_map(${first1HasIdentifier}, ${first1HasLiteral}, false, &[${first1Points}]);\n`;
        ret += `    const FIRST_2_SETS: TokenBitMap = TokenBitMap::build_map(${first2HasIdentifier}, ${first2HasLiteral}, false, &[${first2Points}]);\n\n`;
        ret += `    fn get_error_situation(_: ParseErr) -> Option<Self> {\n`;
        ret += `        None\n`;
        ret += `    }\n\n`;
        ret += `    fn name() -> &'static str { "${func.astTypeName}" }\n`;
        ret += `    type Target = Self;\n`;
        ret += `}\n\n`;


        ret += `impl ${func.astTypeName} {\n`;
        for (const typeName of func.elements
            .filter(element => element.kind !== "terminal")
            .sort((a, b) => a.astTypeName.localeCompare(b.astTypeName))
        ) {
            let returnType;
            switch (typeName.kind) {
                case "boxed":
                    returnType = `ArenaBox<${typeName.astTypeName}>`;
                    break;
                case "option":
                    returnType = `Option<${typeName.astTypeName}>`;
                    break;
                case "optionWithBox":
                    returnType = `Option<ArenaBox<${typeName.astTypeName}>>`;
                    break;
                case "normal":
                    returnType = typeName.astTypeName;
                    break;
                case "repeat":
                    returnType = `ArenaIter<${typeName.astTypeName}>`;
                    break;
            }
            ret += `    pub fn ${typeName.name}(&self) -> &${returnType} {\n`;
            ret += `        &self.${typeName.name}\n`;
            ret += `    }\n\n`;
        }
        ret += `}\n\n`;

        ret += `impl Node for ${func.astTypeName} {\n`;
        ret += `    fn accept<V: ASTVisitor>(&self, visitor: &mut V) -> V::ReturnType {\n`;
        ret += `        visitor.visit_${func.astTypeName}(self)\n`;
        ret += `    }\n`
        ret += `}\n\n`

        return ret;
    }

    private generateHookASTType(func: HookParserFunction): string {
        return `pub use crate::parser::manual_ast::${func.astTypeName};\n\n`;
    }
}
