@root ::= { <top_level_declaration> } ;

<top_level_declaration> ::= <function_declaration> ;

<function_declaration> ::= "fn" <IDENTIFIER> "(" <parameter_list> ")" [ ":" <type_literal> ] <block_expression> ;

<parameter_list> ::= @list_with_comma ( <IDENTIFIER> ) ;

<block_expression> ::= "{" { <statement> } [ <expression> ] "}" ;

<statement> ::=
      <expression> ";"
    | <assignment_statement>
    | <return_statement> ;

<expression> ::= 
      <literal>
    | <function_call> ;

<type_literal> ::= "Int" ;

<assignment_statement> ::= <assignment_keyword> <IDENTIFIER> "=" <expression> ";" ;

<return_statement> ::= "return" [ <expression> ] ";" ;

<literal> ::= <LITERAL> ;

<function_call> ::= <IDENTIFIER> "(" @list_with_comma ( <expression> ) ")" ;

